### ISSUE TITLE
Deadlock quitting pong

### ISSUE THREAD

**Issue by stanliberman** [lirm/aeron-go#15]
Stack:

PC=0x58abb m=0

goroutine 0 [idle]:
runtime.mach_semaphore_wait(0x1103, 0xc40000000e, 0x7fff5fbff580, 0x1dace0, 0x7fff5fbff430, 0x1dace0, 0x7fff5fbff440, 0x4ef13, 0xffffffffffffffff, 0x7fff5fbff470, ...)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/sys_darwin_amd64.s:418 +0xb
runtime.semasleep1(0xffffffffffffffff, 0x7fff5fbff470)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/os_darwin.go:435 +0x4b
runtime.semasleep.func1()
	/usr/local/Cellar/go/1.7/libexec/src/runtime/os_darwin.go:451 +0x33
runtime.systemstack(0x7fff5fbff468)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/asm_amd64.s:314 +0xab
runtime.semasleep(0xffffffffffffffff, 0x0)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/os_darwin.go:452 +0x44
runtime.notesleep(0x1db370)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/lock_sema.go:166 +0x9f
runtime.stopm()
	/usr/local/Cellar/go/1.7/libexec/src/runtime/proc.go:1594 +0xad
runtime.gcstopm()
	/usr/local/Cellar/go/1.7/libexec/src/runtime/proc.go:1798 +0x9a
runtime.findrunnable(0xc420020a00, 0x0)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/proc.go:1848 +0x9a8
runtime.schedule()
	/usr/local/Cellar/go/1.7/libexec/src/runtime/proc.go:2120 +0x14c
runtime.park_m(0xc4200c24e0)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/proc.go:2183 +0x123
runtime.mcall(0x7fff5fbff690)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/asm_amd64.s:240 +0x5b

goroutine 1 [semacquire, 1070 minutes]:
sync.runtime_Semacquire(0xc420096194)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc420096190)
	/usr/local/Cellar/go/1.7/libexec/src/sync/mutex.go:85 +0xd0
github.com/lirm/aeron-go/aeron.(*ClientConductor).releasePublication(0xc420096148, 0xa, 0x0)
	/Users/e11778/gohome/src/github.com/lirm/aeron-go/aeron/clientconductor.go:292 +0x112
github.com/lirm/aeron-go/aeron.(*Publication).Close(0xc42001cbd0, 0xc40000000b, 0xc4200fa060)
	/Users/e11778/gohome/src/github.com/lirm/aeron-go/aeron/publication.go:92 +0x85
main.main()
	/Users/e11778/gohome/src/github.com/lirm/aeron-go/examples/pong/pong.go:112 +0x5e6

goroutine 17 [syscall, 1376 minutes, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.7/libexec/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x1c5140)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/local/Cellar/go/1.7/libexec/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/Cellar/go/1.7/libexec/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [semacquire, 1306 minutes, locked to thread]:
sync.runtime_Semacquire(0xc420096194)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc420096190)
	/usr/local/Cellar/go/1.7/libexec/src/sync/mutex.go:85 +0xd0
github.com/lirm/aeron-go/aeron.(*ClientConductor).releaseSubscription(0xc420096148, 0x8, 0xc4200ea090, 0x1, 0x1, 0x0)
	/Users/e11778/gohome/src/github.com/lirm/aeron-go/aeron/clientconductor.go:377 +0x11e
github.com/lirm/aeron-go/aeron.(*Subscription).Close(0xc4200ce500, 0xc4200e23e0, 0xc4200e23e0)
	/Users/e11778/gohome/src/github.com/lirm/aeron-go/aeron/subscription.go:62 +0xab
github.com/lirm/aeron-go/aeron.(*ClientConductor).Close(0xc420096148, 0x147e38, 0xc420096190)
	/Users/e11778/gohome/src/github.com/lirm/aeron-go/aeron/clientconductor.go:171 +0x1b5
github.com/lirm/aeron-go/aeron.(*ClientConductor).onInterServiceTimeout(0xc420096148, 0x146f592464b84688)
	/Users/e11778/gohome/src/github.com/lirm/aeron-go/aeron/clientconductor.go:550 +0xfd
github.com/lirm/aeron-go/aeron.(*ClientConductor).onHeartbeatCheckTimeouts(0xc420096148, 0x0)
	/Users/e11778/gohome/src/github.com/lirm/aeron-go/aeron/clientconductor.go:563 +0x254
github.com/lirm/aeron-go/aeron.(*ClientConductor).Run(0xc420096148, 0x1c4a40, 0xc42000cc70)
	/Users/e11778/gohome/src/github.com/lirm/aeron-go/aeron/clientconductor.go:207 +0x13c
created by github.com/lirm/aeron-go/aeron.Connect
	/Users/e11778/gohome/src/github.com/lirm/aeron-go/aeron/aeron.go:82 +0x319

goroutine 9 [select, 1376 minutes, locked to thread]:
runtime.gopark(0x147d80, 0x0, 0x13816e, 0x6, 0x18, 0x2)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc420030f30, 0x0, 0x18)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc420030f30)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/usr/local/Cellar/go/1.7/libexec/src/runtime/signal1_unix.go:304 +0x2d1
runtime.goexit()
	/usr/local/Cellar/go/1.7/libexec/src/runtime/asm_amd64.s:2086 +0x1

goroutine 20 [runnable]:
github.com/lirm/aeron-go/aeron.(*Subscription).Poll(0xc4200ce500, 0xc4200ee0c0, 0xa, 0x0)
	/Users/e11778/gohome/src/github.com/lirm/aeron-go/aeron/subscription.go:69
main.main.func3(0xc4200ce500, 0xc4200ee0c0)
	/Users/e11778/gohome/src/github.com/lirm/aeron-go/examples/pong/pong.go:105 +0x3e
created by main.main
	/Users/e11778/gohome/src/github.com/lirm/aeron-go/examples/pong/pong.go:108 +0x57f

rax    0xe
rbx    0x1db260
rcx    0x7fff5fbff3e0
rdx    0x7fff5fbff468
rdi    0x1103
rsi    0x1db261
rbp    0x7fff5fbff418
rsp    0x7fff5fbff3e0
r8     0x7fff5fbff448
r9     0x0
r10    0x0
r11    0x246
r12    0x1ee194258af1d
r13    0x1ef8484969fc0
r14    0x146f66e328b4fa00
r15    0x17c5d8
rip    0x58abb
rflags 0x246
cs     0x7
fs     0x0
gs     0x0

**Comment by stanliberman** [comment]
Deadlock is in onInterServiceTimeout() calling cc.Close(), which will eventually invoke releaseSubscription()
